#!/bin/bash

if [ $# -eq 0 ]
    then
    echo
    echo "ERROR: No arguments supplied !"
    echo
    echo "EXAMPLE: ./createCppProject hello  // without suffix"
    echo
    exit
fi

if [ -d "${@}/" ]
    then
    echo
    echo ${@}' folder is already existed !'
    echo
    exit
    sleep 2
fi

#### make project folder
mkdir ${@} && cd ${@}

#### CMake
echo '
######### CMAKE VERSION ########################
cmake_minimum_required(VERSION 3.16)
set(This '${@}')

######### PROJECT NAME #########################
project(${This} C CXX)

######### FOLDERS ##############################
#include_directories(<USER_FOLDER>)

######### SOURCES ##############################
file(GLOB SOURCES "'${@}'.cpp"
                  #"../<USER_FOLDER>/*cpp"
)

######### OTHERS ###############################
add_executable(${This} ${SOURCES})

######### LIBRARIES ############################
target_link_libraries(${This} PUBLIC
    gtest     # MUST BE ADDED
    gmock     # MUST BE ADDED
    pthread   # MUST BE ADDED
)

################################################
# Created automatically
# GitHub   : https://github.com/bunyamintamar/ProjectCreator.git
' > CMakeLists.txt
echo  'CMakeLists.txt created'


#### builder
echo '
#!/bin/bash

#######################################################################################
# remove old build_'${@}' folder if it exists

if [ -d build_'${@}' ]
    then
    rm -r build_'${@}'
fi

#######################################################################################
# remove old '${@}' file if it exists

if [ -e '${@}' ]
    then
    rm '${@}'
fi

#######################################################################################
# make new build_'${@}' folder

mkdir build_'${@}' && cd build_'${@}'

#######################################################################################
# build

cmake .. && make clean && make

#######################################################################################
# move '${@}' and remove build_'${@}' folder

if [ -e '${@}' ]
    then
    mv '${@}' ..
fi

cd .. && rm -r build_'${@}'

#######################################################################################
# run '${@}'

if [ -e '${@}' ]
    then
    ./'${@}'
    echo && echo 'BUILDED SUCCESSFULY' && echo
else
    echo && echo 'UNSUCCESSFULY !!!' && echo
fi

#######################################################################################
# Created automatically
# GitHub   : https://github.com/bunyamintamar/ProjectCreator.git
' > build_${@}.sh
chmod +x build_${@}.sh
echo  'build_'${@}'.sh created'


#### test file
echo '
#include <iostream>

//#include "<USER_HEADER>"

using namespace std;

int main(int argc, char **argv)
{
    cout << endl << "hello world !" << endl << endl;

    return 0;
}
' > ${@}.cpp
echo  ${@}.cpp created
echo
